version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask:0.0.3
    volumes:
      - ./:/code/
    environment:
      - FLASK_APP=/opt/code/app.py
    command: flask run --host=0.0.0.0 --port=8080
    networks:
      - my-network
    expose:
      - 8080

  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-network
    ports:
      - 80:80

networks:
  my-network: